

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ComputerApp.DAL
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ComputerDbEntities : DbContext
{
    public ComputerDbEntities()
        : base("name=ComputerDbEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Computer> Computers { get; set; }

    public virtual DbSet<Memory> Memories { get; set; }

}

}

