
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ComputerApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Memory
{

    public int MemoryId { get; set; }

    public string Marcar { get; set; }

    public string Tipo { get; set; }

    public int Capacidad { get; set; }

    public int ComputerId { get; set; }



    public virtual Computer Computer { get; set; }

}

}
